env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
plugins:
  - react
rules: {
 "max-len": "off"
}
ignorePatterns: ["coverage", "node_modules", "client/node_modules"]
