name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Up containers
        run: make up

      - name: Install modules
        run: make node_modules TTY=-T

      - name: Run esnlint and solium
        run: make lint TTY=-T

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install
        run: npm install

      - name: Launch Ganache
        run: npx ganache-cli -h 127.0.0.1&

      - name: Coverage
        run: node_modules/.bin/truffle run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Up containers
        run: make up

      - name: Install modules
        run: make node_modules TTY=-T

      - name: Run truffle tests
        run: make truffle-test TTY=-T