name: CI

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install
        run: npm install

      - name: Coverage
        run: npx truffle run coverage

      - name: Coveralls
        run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Up containers
        run: make up

      - name: Install modules
        run: make node_modules TTY=-T

      - name: Install truffle globaly
        run: docker-compose exec -T truffle npm install -g truffle@5.4.32

      - name: Run truffle tests
        run: make truffle-test TTY=-T