name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Show Python version
        run: python --version

      - name: Clone SmartBugs Repo
        run: git clone https://github.com/smartbugs/smartbugs.git

      - name: Remove SmartBugs Results and Install SmartBugs Dependencies
        run: cd smartbugs;rm -r results;pip install -r requirements.txt

      - name: Run SmartBugs Analysis
        run: |
          solidityFiles=($(ls -I Migrations.sol contracts))
          DIR=$(pwd);cd smartbugs
          for sol in "${solidityFiles[@]}"
          do
            echo "Analysing $sol..."
            python smartBugs.py --tool all --file $DIR/contracts/$sol
          done

      - name: Move SmartBugs Results to Parent Directory
        run: |
          [[ -d results ]] && rm -r results
          cd smartbugs
          mv results ../

      - name: Commit SmartBugs Results
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: action@github.com
          message: 'chore: added smartbugs results'
          add: 'results'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Up containers
        run: make up

      - name: Install modules
        run: make node_modules TTY=-T

      - name: Install truffle globaly
        run: docker-compose exec -T truffle npm install -g truffle@5.4.32

      - name: Run truffle tests
        run: make truffle-test TTY=-T