name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: CI=TRUE make build

      - name: Up containers
        run: make up

      - name: Install modules
        run: make node_modules TTY=-T

      - name: Run truffle tests
        run: make truffle-test TTY=-T